// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/**
 * Item in PartnersLogoSlider → Items
 *
 */
export interface PartnersLogoSliderSliceDefaultItem {
    /**
     * Partner Logo field in *PartnersLogoSlider → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: partners_logo_slider.items[].partner_logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    partner_logo: prismicT.ImageField<never>;
}
/**
 * Default variation for PartnersLogoSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PartnersLogoSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PartnersLogoSliderSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<PartnersLogoSliderSliceDefaultItem>>;
/**
 * Item in PartnersLogoSlider → Items
 *
 */
export interface PartnersLogoSliderSlicePartnersLogoSlider2Item {
    /**
     * Partner Logo field in *PartnersLogoSlider → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: partners_logo_slider.items[].partner_logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    partner_logo: prismicT.ImageField<never>;
}
/**
 * PartnersLogoSlider 2 variation for PartnersLogoSlider Slice
 *
 * - **API ID**: `partnersLogoSlider2`
 * - **Description**: `PartnersLogoSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PartnersLogoSliderSlicePartnersLogoSlider2 = prismicT.SharedSliceVariation<"partnersLogoSlider2", Record<string, never>, Simplify<PartnersLogoSliderSlicePartnersLogoSlider2Item>>;
/**
 * Slice variation for *PartnersLogoSlider*
 *
 */
type PartnersLogoSliderSliceVariation = PartnersLogoSliderSliceDefault | PartnersLogoSliderSlicePartnersLogoSlider2;
/**
 * PartnersLogoSlider Shared Slice
 *
 * - **API ID**: `partners_logo_slider`
 * - **Description**: `PartnersLogoSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PartnersLogoSliderSlice = prismicT.SharedSlice<"partners_logo_slider", PartnersLogoSliderSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client;
    }
    namespace Content {
        export type { PartnersLogoSliderSliceDefaultItem, PartnersLogoSliderSliceDefault, PartnersLogoSliderSlicePartnersLogoSlider2Item, PartnersLogoSliderSlicePartnersLogoSlider2, PartnersLogoSliderSliceVariation, PartnersLogoSliderSlice };
    }
}
