// Code generated by Slice Machine. DO NOT EDIT.

import AlternateGrid from './AlternateGrid';
import AtomTags from './AtomTags';
import CallToActionWithImage from './CallToActionWithImage';
import ClientsSlider from './ClientsSlider';
import ContactFormVeedoo from './ContactFormVeedoo';
import ContactInfo from './ContactInfo';
import FaqAccordion from './FaqAccordion';
import FooterVeedoo from './FooterVeedoo';
import HeaderVeedoo from './HeaderVeedoo';
import HeroVeedoo from './HeroVeedoo';
import PartnersLogoSlider from './PartnersLogoSlider';
import PortfolioItems from './PortfolioItems';
import RichText from './RichText';
import Tags from './Tags';
import Testimonial from './Testimonial';

export {
	AlternateGrid,
	AtomTags,
	CallToActionWithImage,
	ClientsSlider,
	ContactFormVeedoo,
	ContactInfo,
	FaqAccordion,
	FooterVeedoo,
	HeaderVeedoo,
	HeroVeedoo,
	PartnersLogoSlider,
	PortfolioItems,
	RichText,
	Tags,
	Testimonial,
};

export const components = {
	alternate_grid: AlternateGrid,
	atom_tags: AtomTags,
	call_to_action_with_image: CallToActionWithImage,
	clients_slider: ClientsSlider,
	contact_form_veedoo: ContactFormVeedoo,
	contact_info: ContactInfo,
	faq_accordion: FaqAccordion,
	footer_veedoo: FooterVeedoo,
	header_veedoo: HeaderVeedoo,
	hero_veedoo: HeroVeedoo,
	partners_logo_slider: PartnersLogoSlider,
	portfolio_items: PortfolioItems,
	text: RichText,
	tags: Tags,
	testimonial: Testimonial,
};
