// Code generated by Slice Machine. DO NOT EDIT.

import AlternateGrid from './AlternateGrid';
import AtomTags from './AtomTags';
import CallToActionWithImage from './CallToActionWithImage';
import FooterVeedoo from './FooterVeedoo';
import HeaderVeedoo from './HeaderVeedoo';
import HeroVeedoo from './HeroVeedoo';
import PartnersLogoSlider from './PartnersLogoSlider';
import RichText from './RichText';
import Tags from './Tags';
import Testimonial from './Testimonial';

export {
	AlternateGrid,
	AtomTags,
	CallToActionWithImage,
	FooterVeedoo,
	HeaderVeedoo,
	HeroVeedoo,
	PartnersLogoSlider,
	RichText,
	Tags,
	Testimonial,
};

export const components = {
	alternate_grid: AlternateGrid,
	atom_tags: AtomTags,
	call_to_action_with_image: CallToActionWithImage,
	footer_veedoo: FooterVeedoo,
	header_veedoo: HeaderVeedoo,
	hero_veedoo: HeroVeedoo,
	partners_logo_slider: PartnersLogoSlider,
	text: RichText,
	tags: Tags,
	testimonial: Testimonial,
};
