// Code generated by Slice Machine. DO NOT EDIT.

import AlternateGrid from './AlternateGrid';
import AtomTags from './AtomTags';
import AudioPlayerWithImage from './AudioPlayerWithImage';
import BlurbHorizontal from './BlurbHorizontal';
import Button from './Button';
import CallToActionWithImage from './CallToActionWithImage';
import ContactFormVeedoo from './ContactFormVeedoo';
import ContactUsGrid from './ContactUsGrid';
import CookieBanner from './CookieBanner';
import CtaTextBlockImageBlock from './CtaTextBlockImageBlock';
import CtaWithBackgroundImage from './CtaWithBackgroundImage';
import Divider from './Divider';
import FaqAccordion from './FaqAccordion';
import FooterVeedoo from './FooterVeedoo';
import GallerySlider from './GallerySlider';
import HeaderVeedoo from './HeaderVeedoo';
import HeaderWithButton from './HeaderWithButton';
import HeroVeedoo from './HeroVeedoo';
import ImageSlice from './ImageSlice';
import LogoGrid from './LogoGrid';
import PageNotFound1 from './PageNotFound1';
import PartnerLogoGridWithDescriptionText from './PartnerLogoGridWithDescriptionText';
import PartnersLogoSlider from './PartnersLogoSlider';
import Person from './Person';
import PortfolioItems from './PortfolioItems';
import PostCarousel from './PostCarousel';
import PostListing from './PostListing';
import PostSlider from './PostSlider';
import RichText from './RichText';
import SimpleErrorPage from './SimpleErrorPage';
import SocialFollowIcons from './SocialFollowIcons';
import Statistics from './Statistics';
import Testimonial from './Testimonial';
import Title from './Title';
import TitleWithDateAndShareIcons from './TitleWithDateAndShareIcons';
import TwoColumnTextBlock from './TwoColumnTextBlock';
import YoutubeVideo from './YoutubeVideo';

export {
	AlternateGrid,
	AtomTags,
	AudioPlayerWithImage,
	BlurbHorizontal,
	Button,
	CallToActionWithImage,
	ContactFormVeedoo,
	ContactUsGrid,
	CookieBanner,
	CtaTextBlockImageBlock,
	CtaWithBackgroundImage,
	Divider,
	FaqAccordion,
	FooterVeedoo,
	GallerySlider,
	HeaderVeedoo,
	HeaderWithButton,
	HeroVeedoo,
	ImageSlice,
	LogoGrid,
	PageNotFound1,
	PartnerLogoGridWithDescriptionText,
	PartnersLogoSlider,
	Person,
	PortfolioItems,
	PostCarousel,
	PostListing,
	PostSlider,
	RichText,
	SimpleErrorPage,
	SocialFollowIcons,
	Statistics,
	Testimonial,
	Title,
	TitleWithDateAndShareIcons,
	TwoColumnTextBlock,
	YoutubeVideo,
};

export const components = {
	alternate_grid: AlternateGrid,
	atom_tags: AtomTags,
	audio_player_with_image: AudioPlayerWithImage,
	blurb: BlurbHorizontal,
	button: Button,
	call_to_action_with_image: CallToActionWithImage,
	contact_form_veedoo: ContactFormVeedoo,
	contact_info: ContactUsGrid,
	cookie_banner: CookieBanner,
	cta_text_block_image_block: CtaTextBlockImageBlock,
	cta_with_background_image: CtaWithBackgroundImage,
	divider: Divider,
	faq_accordion: FaqAccordion,
	footer_veedoo: FooterVeedoo,
	gallery_slider: GallerySlider,
	header_veedoo: HeaderVeedoo,
	header_with_button: HeaderWithButton,
	hero_veedoo: HeroVeedoo,
	image: ImageSlice,
	logo_grid: LogoGrid,
	page_not_found1: PageNotFound1,
	partner_logo_grid_with_description_text: PartnerLogoGridWithDescriptionText,
	partners_logo_slider: PartnersLogoSlider,
	person: Person,
	portfolio_items: PortfolioItems,
	post_carousel: PostCarousel,
	post_listing: PostListing,
	post_slider: PostSlider,
	rich_text: RichText,
	simple_error_page: SimpleErrorPage,
	social_follow_icons: SocialFollowIcons,
	statistics: Statistics,
	testimonial: Testimonial,
	title: Title,
	title_with_date_and_share_icons: TitleWithDateAndShareIcons,
	two_column_text_block: TwoColumnTextBlock,
	youtube_video: YoutubeVideo,
};
